###
FROM registry.access.redhat.com/ubi8/openjdk-17


# ARG RUN_JAVA_VERSION=1.3.5

# ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# COPY target/lib/* /deployments/lib/
COPY target/classes/* /deployments/classes/
COPY target/*.jar /deployments/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]
